---

# Login variables
palo_provider:
  ip_address: '{{ ansible_host }}'
  username: '{{ vault_username }}'
  password: '{{ vault_password }}'
  api_key: '{{ vault_api_key }}'

# Connection variables
ansible_connection: local

...
