---

# Login variables
palo_provider:
  ip_address: '{{ ansible_host }}'
  username: 'ansible'
#  password: '{{ lookup("ansible.builtin.env", "PANOS_PASSWORD") }}'
  api_key: '{{ lookup("ansible.builtin.env", "PANOS_API_KEY") }}'

# Comment out either 'password' or 'api_key'

...
