---

# DESTINATION NAT
- name: HTTPS DNAT - 4443to443
  paloaltonetworks.panos.panos_nat_rule:
    provider: '{{ palo_provider }}'
    rule_name: 'HTTPS DNAT'
    group_tag: 'Public Policies'
    source_zone: ['LAN', 'INTERNET']
    destination_zone: 'INTERNET'
    source_ip: 'any'
    destination_ip: 'fw-outside-ip'
    service: 'tcp-4443'
    dnat_address: 'FW01_LOOPBACK999'
    dnat_port: "443"
    state: present
# This role needs some work
...
