---

# Default variables

admin_roles:
  - value: |
      <entry name='{{ admin_role_name }}'>
        <role>
          <device>
            <webui/>
            <xmlapi>
              <config>enable</config>
              <op>enable</op>
              <commit>enable</commit>
            </xmlapi>
            <restapi/>
          </device>
        </role>
        <description>{{ admin_role_name }} Admin Role</description>
      </entry>

...
